# Build output directory (relative to Makefile location)
output_dir_host: output/wheelhouse

# Target environment for this build run
build_target:
  python_version: "3.11" # Target Python version (e.g., 3.8, 3.9, 3.10)
  cuda_version: "12.8" # Target CUDA version (e.g., 11.7, 11.8, 12.1)
  pytorch_version: "2.7.0" # Target PyTorch version (used to select base image)
  # platform: "linux_x86_64" # Platform is usually detected inside the container

# List of projects to build
projects:

  - name: flash-attention
    repo_url: https://github.com/Dao-AILab/flash-attention.git
    repo_ref: v2.7.4.post1
    force_no_isolation: true

  - name: SageAttention
    repo_url: https://github.com/thu-ml/SageAttention.git
    repo_ref: main
    force_no_isolation: true

  - name: GroundingDINO
    # https://github.com/IDEA-Research/GroundingDINO.git
    repo_url: https://github.com/kenshi84/GroundingDINO.git
    repo_ref: main # Branch, tag, or commit hash (optional, defaults to clone default branch)
    force_no_isolation: true
    build_env:
      TORCH_CUDA_ARCH_LIST: 8.9;9.0;9.0a
    # build_command: "python setup.py bdist_wheel --custom-flag" # Optional custom build command

  - name: llama-cpp-python
    repo_url: https://github.com/abetlen/llama-cpp-python.git
    repo_ref: v0.3.9
    build_env:
      CMAKE_ARGS: "-DGGML_CUDA=on"

  - name: diso
    repo_url: https://github.com/SarahWeiii/diso.git
    repo_ref: main
    force_no_isolation: true
    build_env:
      TORCH_CUDA_ARCH_LIST: 8.9;9.0;9.0a

  # - name: another_project
  #   repo_url: https://gitlab.com/your_org/another_project.git
  #   repo_ref: v1.2.3
    # dependencies: # Optional dependencies to install before build
    #  - numpy==1.24.*

# --- Configuration for Dockerfile Generation ---
# Mapping PyTorch/CUDA versions to Docker Hub base images
# (Adjust this based on available PyTorch official images)
pytorch_base_images:
  "2.1.0":
    "11.8": "pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel"
    "12.1": "pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel"
  "2.6.0":
    "12.4": "pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel"
  "2.7.0":
    "12.8": "pytorch/pytorch:2.7.0-cuda12.8-cudnn9-devel"
  # Add more mappings as needed

# Additional packages to install in the Docker image via apt
apt_packages:
  - git
  - build-essential
  - ninja-build
  - g++-11
  - gcc-11
  - cmake
  # Add other common dependencies here

# Additional packages to install in the Docker image via pip
pip_packages:
  - setuptools
  - wheel
  - build
  - PyYAML # Needed by build_script.py to parse config
